version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8081:8081
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000 
    depends_on:
      - mongo
  
    